---
title: "filter_join"
author: "Evan Roybal"
date: "12/20/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#install and load packages
```{r}
library(tidyverse)
library(readxl)
library(here)
library(kableExtra)
```

#read in data files
```{r}
fish <- read_csv(here("data", "fish.csv"))
kelp_abur <- read_excel(here("data", "kelp.xlsx"), sheet = "abur")
```

#practice with the filter() function from dplyr
```{r}
fish_garibaldi <- fish %>%
  filter(common_name == "garibaldi")

#attempt to do it on my own
fish_mohk <- fish %>%
  filter(site == "mohk")

#using inequality signs with filter() function
fish_over50 <- fish %>%
  filter(total_count >= 50)

#using OR operation with filter() function to keep more than one observation
fish_3sp <- fish %>%
  filter(common_name == "garibaldi" |
           common_name == "blacksmith" |
           common_name == "black surfpench")
#using %in% operation with filter() function to select multiple matches in the same variable
fish_3p_2 <- fish %>%
  filter(common_name %in% c("garibaldi", "blacksmith", "black surfpench"))

#practice
fish_gar_2016 <- fish %>%
  filter(year == 2016 | common_name == "garibaldi")

#using the AND operator
aque_2018 <- fish %>%
  filter(year == 2018, site == "aque")

#practice
low_gb_wr <- fish %>%
  filter(common_name %in% c("garibaldi", "rock wrasse"), total_count <= 10)

#using str_detect() function from the stringr package to keep observations that match a specified pattern
fish_bl <- fish %>%
  filter(str_detect(common_name, pattern = "black"))

#practice with str_detect()
fish_it <- fish %>%
  filter(str_detect(common_name, pattern = "it"))

#can add negate = TRUE into str_detect() to exclude observations with a specific string pattern
fish_negate <- fish %>%
  filter(str_detect(common_name, pattern = "it", negate = TRUE))
```

#using dplyr::*join() functions to merge data frames
```{r}
#fixing kelp_abur dataset to be able to merge with fish dataset correctly
#kelp_abur <- kelp_abur %>%
  #mutate(year = year - 2000)
#using full_join() to combine fish and kelp_abur data frames with all data being preserved
abur_kelp_fish <- kelp_abur %>%
  full_join(fish, by = c("year", "site"))

#practice with left_join()
kelp_fish_left <- kelp_abur %>%
  left_join(fish, by = c("year", "site"))

#inner_join()
kelp_fish_injoin <- kelp_abur %>%
  inner_join(fish, by = c("year", "site"))

#combining filter() and join()
my_fish_join <- fish %>%
  filter(year == 2017, site == "abur") %>%
  left_join(kelp_abur, by = c("year", "site")) %>%
  mutate(fish_per_kelp_fronds = total_count / total_fronds)
```

#using knitr:kable() and functions in the kableExtra package
```{r}
#kable(my_fish_join)

#using kableExtra functions to spruce up tables in the knitted document
my_fish_join %>%
  kable() %>%
  kable_styling(bootstrap_options = "striped",
                full_width = FALSE)
```

