---
title: "my_tidying.Rmd"
author: "Evan Roybal"
date: "12/18/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#Load Packages
```{r}
library('tidyverse')
library('here')
#don't forget to uncomment install.packages('janitor') if you currently don't have it installed
#install.packages('janitor')
library('janitor')
library('readxl')
```

#read in data
```{r}
inverts <- read_excel(here("data", "inverts.xlsx"))
```

#use pivot_longer command from tidyr
```{r}
inverts_long <- pivot_longer(data = inverts,
                             cols = '2016':'2018',
                             names_to = 'year',
                             values_to = 'sp_count')

inverts_long <- inverts_long %>%
  mutate(year = as.numeric(year))
#changes the year column from character class to numeric class
```

#use pivot_shorter
```{r}
inverts_wide <- inverts_long %>%
  pivot_wider(names_from = common_name,
              values_from = sp_count)
```

#use clean_names() function from janitor package
```{r}
inverts_wide <- inverts_wide %>%
  clean_names()
```

#use unite() function from tidyr package
```{r}
inverts_unite <- inverts_long %>%
  unite(col = "site_year",
        c(site, year),
        sep = "_")
```

#practice with unite() function
```{r}
inverts_moyr <- inverts_long %>%
  unite(col = "mo_yr",
        c(month, year),
        sep = "/")

#unite() function can also merge info from more than 2 columns
inverts_triple_unite <- inverts_long %>%
  unite(col = "year_site_name",
        c(year, site, common_name),
        sep = "-")
```

#use separate() function from tidyr package
```{r}
inverts_sep <- inverts_unite %>%
  separate(site_year, into = c("my_site", "my_year"))
```

#use str_replace() function from stringr to replace specific strings with other strings
```{r}
ca_abbr <- inverts %>%
  mutate(
    common_name =
      str_replace(common_name,
                  pattern = "california",
                  replacement = "CA")
  )
```

