---
title: "pivot_lobsters.Rmd"
author: "Evan Roybal"
date: "9/10/2020"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
##attach libraries
```{r}
library(tidyverse)
library(readxl)
library(here)
library(skimr) #install.packages('skimr')
library(kableExtra) #install.packages('kableExtra')
```
#read in lobsters.xlsx file
```{r}
lobsters <- read_xlsx(here("data/lobsters.xlsx"), skip = 4)

skimr::skim(lobsters)

#practice creating a pivot table in R
siteyear_summary <- lobsters %>%
  group_by(site, year) %>%
  summarize(count_by_year = n(),
            mean_size_mm = mean(size_mm, na.rm = TRUE),
            sd_size_mm = sd(size_mm, na.rm = TRUE),
            median_size_mm = median(size_mm, na.rm = TRUE))

#graphing siteyear_summary
ggplot(data = siteyear_summary, aes(x = year, y = median_size_mm, color = site)) +
  geom_line()

#saving site_year_summary graph
ggsave(here('figures', 'lobsters-line.png'))
```

There are `r nrow(lobsters)` total lobsters included in this report
