---
title: "Creating graphs in R with 'ggplot2'"
author: "Evan Roybal"
date: "9/9/2020"
output: html_document

#Plots with ggplot2

```{r}
#loading libraries for data science
library(tidyverse)
library(readxl)
library(here)
```

```{r}
#loading in ca_np.csv file and ci_np.xlsx
ca_np <- read_csv(here("data", "ca_np.csv"))
ci_np <- read_excel(here("data", "ci_np.xlsx"))
```

```{r}
#ggplot attempt with ci_np data
gg_base <- ggplot(data = ci_np, aes(x = year, y = visitors))

gg_base +
  geom_point(color = "red",
             pch = 17,
             size = 4,
             alpha = 0.5)
gg_base +
  geom_col( color = "blue",
            alpha = .75,
            size = 5)
gg_base +
  geom_area()
gg_base +
  geom_line(
    color = "purple",
    linetype = "dashed"
    )
#practie with variable mapping or whatever this is
gg_base +
  geom_point(
    aes(size = visitors,
        color = visitors),
    alpha = 0.5) +
  theme_minimal()
    
gg_base +
  geom_col(aes(fill = visitors)) +
  labs(
    x = "Year",
    y = "Annual park visitors",
    title = "Channel Islands NP Visitation",
    subtitle = "(1963 - 2016)"
    )
    
#Multi-series and faceting ggplot graph practice
gg_np <- ggplot(data = ca_np, aes(x = year, y = visitors, group = park_name))

gg_np +
  geom_line(show.legend = FALSE) +
  theme_light() +
  labs(x = "year", y = "annual visitors") +
  facet_wrap(~ park_name)
  
ggsave(here("figures", "np_graph.jpg"), dpi = 180, width = 8, height = 7)
```

